sudo: required

services:
  - docker

before_script:
  - docker-compose up -d

script:
  - docker exec backend python3 manage.py test

after_script:
  - docker-compose down --remove-orphans

deploy:
  provider: heroku
  api_key:
    secure: QiiPePlji6By+QpGwgnUHXxbtN6cAHT8EgMmTzGrOO9W8gZKkJK6jzhRZOFXR8KYXzttaOcn6Vg3NZEmdiwJyKdse0PYLZg3ZkB63WCPIfxJbKIFgMHINg0oXJCYZZ9yUUfXiBDJNUiQHzjXej8KrDXwMAowBv/VL42F5O5nS/aFpUuWzHnkQXk+2hAyaSMoD692bn7DoMaJ061Uct2SZqOJaGSRlExPVogHM+goUbyhDOtdssiv509k4XpXxTytV2ALJShy7mzJxMb3fL8KpLlV7T8RxofwIDNMhX/mMFFySmxrCAB4l9Uub7u7H3T7kzoYuxw+69T29KZ/CGRyyDwHs1cPqvzPq4goqIZ7qhCs+ohtDPnMJ+D0FDI/5omubIrTcPIbGjZQN112z9LEt1HOTEq6eNDVsKLV0Hy8DJnOgXsnoimNrKj2X2pR/vXIL1Q6nSq/J+zLgoV7XaWz2fgLsEkGQiCnqwplb0KrHzKGhaiF5spNCbcVQD+HD97+qJTQ9/KXcuvoy/YYnSedcfJRkjFouPq0NEvHzBi58Vt1sGuTlpE++hIuklA3LseSqVWcj69M41ZWVok+ewl74ZMYOBKe6dLO68p8CHepRSKbj+hNYf5Y1OdNFOVxb7WhThn/kxq8NqgsXTzRZ8RNg6DEsL/VUXczWp8E7AmUGkQ=
  on: development