version: '3'

services:
  backend:
    container_name: backend
    build: .
    command: /bin/bash -l -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    tty: true