site_name: EconomizAqui

pages:
  - Home: index.md

  - Metodologia:
    - Desenho da Metodologia: Metodologia/Desenho-da-Metodologia.md
    - Modelagem da Metodologia:
      - Artefatos de Desenvolvimento:
        - Documento de Visão: Metodologia/Modelagem-da-Metodologia/Artefatos-de-Desenvolvimento/Documento-de-Visão.md
        - Elicitação de Requisitos: Metodologia/Modelagem-da-Metodologia/Artefatos-de-Desenvolvimento/Elicitação-de-Requisitos.md
        - NFR Framework: Metodologia/Modelagem-da-Metodologia/Artefatos-de-Desenvolvimento/NFR-Framework.md
      - Artefatos de Modelagem do Sistema:
        - Diagrama de Caso de Uso: Metodologia/Modelagem-da-Metodologia/Artefatos-de-Modelagem-do-Sistema/Diagrama-de-Caso-de-Uso.md
        - Diagrama de Domínio: Metodologia/Modelagem-da-Metodologia/Artefatos-de-Modelagem-do-Sistema/Diagrama-de-Domínio.md
      - Artefatos Organizacionais:
        - Plano de Gerenciamento de Riscos: Metodologia/Modelagem-da-Metodologia/Artefatos-Organizacionais/Plano-de-Gerenciamento-de-Riscos.md

  - Dinâmica 1:
    - 5W2H: Dinâmica-1/5W2H.md
    - Léxicos: Dinâmica-1/Léxicos.md
    - Mapa-Mental: Dinâmica-1/Mapa-Mental.md
    - Rich Pictures: Dinâmica-1/Rich-Picture.md
    - Storyboard: Dinâmica-1/Storyboard.md
