site_name: EconomizAqui
repo_name: EconomizAqui
repo_url: https://github.com/EconomizAqui/EconomizAqui

pages:
  - Home: index.md

  - I. Artefatos genéricos:
    - Rich Pictures: Requisitos/Elicitação/Rich-Picture.md
    - Storyboard: Requisitos/Elicitação/Storyboard.md
    - Mapa Mental: Requisitos/Elicitação/Mapa-Mental.md
    - Léxicos: Requisitos/Modelagem/Inicial/Léxicos.md
    - 5W2H: Requisitos/Elicitação/5W2H.md
  
  - II. Desenho da metodologia:
    - Metodologia: Metodologia/Desenho-da-Metodologia.md

  - III. Aderência à metodologia:
    - Documento de Visão: Artefatos/Desenvolvimento/Documento-de-Visão.md
    - Brainstorming: Requisitos/Elicitação/Brainstorming.md
    - Elicitação de Requisitos: Requisitos/Elicitação/Elicitação-de-Requisitos.md
    - Plano de Gerenciamento de Riscos: Artefatos/Organizacional/Plano-de-Gerenciamento-de-Riscos.md
    - Detalhamento dos Riscos: Artefatos/Organizacional/Detalhamento-dos-Riscos.md
    - Diagrama de Caso de Uso: Requisitos/Modelagem/Tradicional/Diagrama-de-Caso-de-Uso.md
    - Diagrama de Domínio: Requisitos/Modelagem/Tradicional/Diagrama-de-Domínio.md
    - NFR Framework: Requisitos/Modelagem/Intencional/NFR-Framework.md
    - Backlog do Produto: Requisitos/Modelagem/Ágil/Backlog-do-Produto.md
    - Roadmap: Requisitos/Modelagem/Ágil/Roadmap.md

  - IV. Padrões de Projeto:
    - GOF: Padrões/GOF.md

  - V. Arquitetura de Projeto:
    - Arquitetura

  - Iniciativas Extras:
    - Atas de Reunião:
      - Ata 01: Atas-de-Reuniões/Ata-01.md
      - Ata 02: Atas-de-Reuniões/Ata-02.md
      - Ata 03: Atas-de-Reuniões/Ata-03.md
      - Ata 04: Atas-de-Reuniões/Ata-04.md
      - Ata 05: Atas-de-Reuniões/Ata-05.md
      - Ata 06: Atas-de-Reuniões/Ata-06.md
    - Configuração de Software e Políticas de Repositório: Artefatos/Desenvolvimento/Configuração-de-Software-e-Políticas-de-Repositório.md

theme:
  name: 'material'

markdown_extensions:
  - toc:
      permalink: True