site_name: EconomizAqui

pages:
  - Home: index.md

  - Metodologia: Metodologia/Desenho-da-Metodologia.md

  - Artefatos:
      - Desenvolvimento:
        - Configuração de Software e Políticas de Repositório: Artefatos/Desenvolvimento/Configuração-de-Software-e-Políticas-de-Repositório.md
        - Documento de Visão: Artefatos/Desenvolvimento/Documento-de-Visão.md
      - Organizacional:
        - Plano de Gerenciamento de Riscos: Artefatos/Organizacional/Plano-de-Gerenciamento-de-Riscos.md
        - Detalhamento dos Riscos: Artefatos/Organizacional/Detalhamento-dos-Riscos.md

  - Requisitos:
    - Elicitação:
      - Elicitação de Requisitos: Requisitos/Elicitação/Elicitação-de-Requisitos.md
      - 5W2H: Requisitos/Elicitação/5W2H.md
      - Brainstorming: Requisitos/Elicitação/Brainstorming.md
      - Mapa Mental: Requisitos/Elicitação/Mapa-Mental.md
      - Rich Pictures: Requisitos/Elicitação/Rich-Picture.md
      - Storyboard: Requisitos/Elicitação/Storyboard.md
    - Modelagem:
      - Ágil:
        - Backlog do Produto: Requisitos/Modelagem/Ágil/Backlog-do-Produto.md
        - Roadmap: Requisitos/Modelagem/Ágil/Roadmap.md
      - Inicial:
        - Léxicos: Requisitos/Modelagem/Inicial/Léxicos.md
      - Intencional:
        - NFR Framework: Requisitos/Modelagem/Intencional/NFR-Framework.md
      - Tradicional:
        - Diagrama de Caso de Uso: Requisitos/Modelagem/Tradicional/Diagrama-de-Caso-de-Uso.md
        - Diagrama de Domínio: Requisitos/Modelagem/Tradicional/Diagrama-de-Domínio.md

  # - Padrões de Projeto:

  # - Arquitetura de Projeto:

  - Atas de Reuniões:
    - Ata 01: Atas-de-Reuniões/Ata-01.md
    - Ata 02: Atas-de-Reuniões/Ata-02.md
    - Ata 03: Atas-de-Reuniões/Ata-03.md
    - Ata 04: Atas-de-Reuniões/Ata-04.md
    - Ata 05: Atas-de-Reuniões/Ata-05.md
