site_name: EconomizAqui

pages:
  - Home: index.md

  - Metodologia:
    - Desenho da Metodologia: Metodologia/Desenho-da-Metodologia.md
    - Modelagem da Metodologia:
      - Documento de Visão: Metodologia/Modelagem-da-Metodologia/Documento-de-Visão.md

  - Elicitação de Requisitos:
    - 5W2H: Elicitação-de-Requisitos/5W2H.md
    - Léxicos: Elicitação-de-Requisitos/Léxicos.md
    - Mapa-Mental: Elicitação-de-Requisitos/Mapa-Mental.md
    - Rich Pictures: Elicitação-de-Requisitos/Rich-Picture.md
    - Storyboard: Elicitação-de-Requisitos/Storyboard.md
