site_name: EconomizAqui

pages:
  - Home: index.md

  - Elicitação de Requisitos:
    - Rich Pictures: Elicitação-de-Requisitos/Rich-Picture.md
    - Storyboard: Elicitação-de-Requisitos/Storyboard.md
